---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['main', 'release-*']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.branch_check.outputs.skip }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Validate branch name
        id: branch_check
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          echo "Branch: $BRANCH"

          if [[ "$BRANCH" == release-* ]]; then
            if [[ "$BRANCH" =~ ^release-[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
              echo "✅ Valid release branch"
              echo "skip=false" >> $GITHUB_OUTPUT
            else
              echo "⚠️ Invalid release branch → skipping pipeline"
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "Not a release branch"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: "Verify Branch Name"
        if: steps.branch_check.outputs.skip != 'true'
        uses: open-edge-platform/orch-ci/verify-branch-name@bf82f7924caaac6ba2f388b6ec6ac4edd65f48ee  # yamllint disable-line rule:line-length

  post-merge-pipeline:
    needs: pre-checks
    if: needs.pre-checks.outputs.skip != 'true'
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@bf82f7924caaac6ba2f388b6ec6ac4edd65f48ee  # yamllint disable-line rule:line-length
    with:
      run_version_check: true
      run_dep_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: true
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}

  publish-documentation:
    permissions:
      contents: read
      pull-requests: read
      issues: write
    needs: pre-checks
    if: needs.pre-checks.outputs.skip != 'true'
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a95228137803b756aae327668c115db235802982  # yamllint disable-line rule:line-length
    with:
      simple_mode: false
      branch_pattern: '^(main|release-[0-9]+\.[0-9]+.*)$'
      switch_main_to_dev: true
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
